"""add name to item

Revision ID: 0e393c06904b
Revises: 9837d08f125a
Create Date: 2022-04-19 07:45:39.829782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e393c06904b'
down_revision = '9837d08f125a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'name')
    # ### end Alembic commands ###
