"""add tenant id to user

Revision ID: 3f1e8183dcc4
Revises: 7dc0959e9ec0
Create Date: 2022-04-19 03:57:27.932641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1e8183dcc4'
down_revision = '7dc0959e9ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
