"""first m

Revision ID: 9837d08f125a
Revises: 
Create Date: 2022-04-19 07:39:17.862470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9837d08f125a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ptype', sa.String(), nullable=False),
    sa.Column('v0', sa.String(), nullable=True),
    sa.Column('v1', sa.String(), nullable=True),
    sa.Column('v2', sa.String(), nullable=True),
    sa.Column('v3', sa.String(), nullable=True),
    sa.Column('v4', sa.String(), nullable=True),
    sa.Column('v5', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('v0', 'v1', 'v2', name='_v0_v1_uc')
    )
    op.create_index(op.f('ix_casbin_rule_id'), 'casbin_rule', ['id'], unique=False)
    op.create_index(op.f('ix_casbin_rule_v0'), 'casbin_rule', ['v0'], unique=False)
    op.create_index(op.f('ix_casbin_rule_v2'), 'casbin_rule', ['v2'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_casbin_rule_v2'), table_name='casbin_rule')
    op.drop_index(op.f('ix_casbin_rule_v0'), table_name='casbin_rule')
    op.drop_index(op.f('ix_casbin_rule_id'), table_name='casbin_rule')
    op.drop_table('casbin_rule')
    # ### end Alembic commands ###
