"""add tenant id to item table

Revision ID: a3ccf546cc5d
Revises: 0e393c06904b
Create Date: 2022-04-21 08:13:53.457944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ccf546cc5d'
down_revision = '0e393c06904b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_items_tenant_id'), 'items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_tenant_id'), table_name='items')
    op.drop_column('items', 'tenant_id')
    # ### end Alembic commands ###
